# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PLUGIN_MARKET_PAT }}
          user: dsh-plugins
          template: classic
          base: header, activity, community
          config_octicon: yes
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_other: no
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          repositories_forks: yes
          plugin_stargazers: yes
          plugin_stargazers_days: 365
          plugin_stargazers_charts_type: graph
          plugin_repositories: yes
          plugin_repositories_featured: dsh-plugins/dsh-loader, dsh-plugins/dsh-launcher
          plugin_traffic: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, star
